
services:
  # MySQL Database Service
  mysql_db:
    container_name: mysql-db-pharmacy
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yassir@2002
      MYSQL_DATABASE: pharmacyDB
      MYSQL_USER: pharmacyuser
      MYSQL_PASSWORD: yassir@2002
      MYSQL_ROOT_PASSWORD_FOR_HEALTHCHECK: yassir@2002
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - pharmacy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p yassir@2002"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  pharmacy-backend:
    container_name: pharmacy-backend-api
    image: pms/pms:1.0.0
    ports:
      - "8083:8083"
    networks:
      - pharmacy-network
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:mysql://mysql_db:3306/pharmacyDB
      - SPRING_DATASOURCE_USERNAME=pharmacyuser
      - SPRING_DATASOURCE_PASSWORD=yassir@2002
      - ACTIVE_PROFILE=${PROFILE:-dev}
    restart: unless-stopped

  pharmacy-frontend:
    container_name: pharmacy-backend-front
    image: pms/pms-ui:1.0.0
    ports:
      - "4200:80"
    networks:
      - pharmacy-network
    depends_on:
      - pharmacy-backend
    restart: unless-stopped

networks:
  pharmacy-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local