global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pharmacy-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pharmacy-backend:8083']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']